version: '3.8'

services:
  db:
    image: postgres:15
    container_name: skinscope_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skinscope
      POSTGRES_PASSWORD: skinscope
      POSTGRES_DB: skinscope
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
