version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dermaai_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dermaai
      POSTGRES_PASSWORD: dermaai
      POSTGRES_DB: dermaai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
